# Generated by Django 6.0.6 on 2026-06-23 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(help_text='한자', max_length=10, unique=True)),
                ('meaning_ko', models.TextField(help_text='한국어 뜻 (예: 바칠 공)')),
                ('components', models.TextField(blank=True, help_text='구성자')),
                ('stroke_count', models.PositiveIntegerField(blank=True, help_text='획수', null=True)),
                ('on_reading', models.CharField(blank=True, help_text='음독', max_length=100)),
                ('kun_reading', models.CharField(blank=True, help_text='훈독', max_length=100)),
                ('meaning_ja', models.TextField(blank=True, help_text='일본어 뜻')),
                ('jlpt_level', models.CharField(blank=True, choices=[('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3'), ('N4', 'N4'), ('N5', 'N5')], max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '한자',
                'verbose_name_plural': '한자',
                'indexes': [models.Index(fields=['jlpt_level'], name='content_kan_jlpt_le_1aa45f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(help_text='단어 표기(히라가나/한자 혼재)', max_length=100)),
                ('word_type', models.CharField(choices=[('kana', '가나'), ('kanji', '한자')], max_length=10)),
                ('reading', models.CharField(blank=True, help_text='읽기', max_length=100)),
                ('pos', models.CharField(blank=True, help_text='품사', max_length=50)),
                ('jlpt_level', models.CharField(blank=True, choices=[('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3'), ('N4', 'N4'), ('N5', 'N5')], max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '단어',
                'verbose_name_plural': '단어',
                'indexes': [models.Index(fields=['surface'], name='content_wor_surface_489629_idx'), models.Index(fields=['jlpt_level'], name='content_wor_jlpt_le_aef320_idx')],
            },
        ),
        migrations.CreateModel(
            name='WordMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sense_no', models.PositiveIntegerField(help_text='의미 순번(1,2,3…)')),
                ('meaning_ko', models.TextField(help_text='정제된 개별 뜻')),
                ('note', models.TextField(blank=True, help_text='부가 설명(예: 정중한 말)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='content.word')),
            ],
            options={
                'verbose_name': '단어 뜻',
                'verbose_name_plural': '단어 뜻',
                'ordering': ['word', 'sense_no'],
                'constraints': [models.UniqueConstraint(fields=('word', 'sense_no'), name='uniq_word_sense_no')],
            },
        ),
    ]
