# Generated by Django 6.0.6 on 2026-06-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='meaning_ko_detail',
            field=models.TextField(blank=True, default=''),
        ),
    ]
