# Generated by Django 6.0.6 on 2026-06-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_kanji_meaning_ko_detail'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kanji',
            new_name='tbl_content_jlpt_le_9acebb_idx',
            old_name='content_kan_jlpt_le_1aa45f_idx',
        ),
        migrations.RenameIndex(
            model_name='word',
            new_name='tbl_content_surface_34b8b7_idx',
            old_name='content_wor_surface_489629_idx',
        ),
        migrations.RenameIndex(
            model_name='word',
            new_name='tbl_content_jlpt_le_3f404c_idx',
            old_name='content_wor_jlpt_le_aef320_idx',
        ),
        migrations.AlterModelTable(
            name='kanji',
            table='tbl_content_kanji',
        ),
        migrations.AlterModelTable(
            name='word',
            table='tbl_content_word',
        ),
        migrations.AlterModelTable(
            name='wordmeaning',
            table='tbl_content_wordmeaning',
        ),
    ]
