# Generated by Django 6.0.6 on 2026-06-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_content_kan_jlpt_le_1aa45f_idx_tbl_content_jlpt_le_9acebb_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(help_text='가나 글자(예: あ, ア, きゃ)', max_length=4)),
                ('romaji', models.CharField(help_text='로마자 읽기(예: a, kya)', max_length=8)),
                ('script', models.CharField(choices=[('hira', '히라가나'), ('kata', '가타카나')], max_length=4)),
                ('kind', models.CharField(choices=[('seion', '청음'), ('dakuten', '탁음·반탁음'), ('youon', '요음')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '가나',
                'verbose_name_plural': '가나',
                'db_table': 'tbl_content_kana',
                'indexes': [models.Index(fields=['script', 'kind'], name='idx_kana_script_kind')],
                'constraints': [models.UniqueConstraint(fields=('character', 'script'), name='uniq_kana_char_script')],
            },
        ),
    ]
