# Generated by Django 6.0.6 on 2026-06-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_kana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanji',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='word',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wordmeaning',
            name='created_at',
        ),
    ]
