# Generated by Django 6.0.6 on 2026-06-27 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_created_at_from_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordmeaning',
            name='note',
        ),
    ]
