# Generated by Django 6.0.6 on 2026-07-01 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_note_from_wordmeaning'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanaExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(help_text='단어 가나 표기 (예: あか)', max_length=20)),
                ('kanji', models.CharField(blank=True, help_text='한자 표기 (예: 赤), 없으면 빈 문자열', max_length=20)),
                ('meaning_ko', models.CharField(help_text='한국어 뜻 (예: 빨강)', max_length=100)),
                ('kana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='content.kana')),
            ],
            options={
                'verbose_name': '가나 예시 단어',
                'verbose_name_plural': '가나 예시 단어',
                'db_table': 'tbl_content_kanaexample',
                'constraints': [models.UniqueConstraint(fields=('kana', 'surface'), name='uniq_kanaexample_kana_surface')],
            },
        ),
    ]
