# Generated by Django 6.0.6 on 2026-07-03 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_kanaexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_no', models.PositiveIntegerField(help_text='단어 내 예문 순서(1,2,3)')),
                ('origin', models.TextField(help_text='한자 표기 일본어 문장')),
                ('reading', models.TextField(blank=True, default='', help_text='전부 가나로 풀어쓴 읽기')),
                ('translation', models.TextField(blank=True, default='', help_text='한국어 번역')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='content.word')),
            ],
            options={
                'verbose_name': '단어 예문',
                'verbose_name_plural': '단어 예문',
                'db_table': 'tbl_content_wordexample',
                'ordering': ['word', 'sort_no'],
                'constraints': [models.UniqueConstraint(fields=('word', 'sort_no'), name='uniq_wordexample_word_sort_no')],
            },
        ),
    ]
