# Generated by Django 6.0.6 on 2026-07-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_wordexample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kana',
            name='created_at',
        ),
    ]
