# Generated by Django 6.0.6 on 2026-06-23 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.BigIntegerField(default=0, help_text='현재 캐시 (≥ 0)')),
                ('total_earned', models.BigIntegerField(default=0, help_text='누적 적립 합(통계용)')),
                ('total_used', models.BigIntegerField(default=0, help_text='누적 사용 합(통계용)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '지갑',
                'verbose_name_plural': '지갑',
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='출석 일자')),
                ('streak_count', models.PositiveIntegerField(default=1, help_text='연속 출석 일수')),
                ('bonus_cash', models.PositiveIntegerField(default=0, help_text='지급 보너스 캐시')),
                ('is_cycle_reward', models.BooleanField(default=False, help_text='7일 사이클 대형 보너스 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '출석',
                'verbose_name_plural': '출석',
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_attendance_user_date')],
            },
        ),
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('normal', '일반'), ('rare', '레어'), ('jackpot', '잭팟')], max_length=10)),
                ('status', models.CharField(choices=[('unopened', '미개봉'), ('opened', '개봉')], default='unopened', max_length=10)),
                ('reward_cash', models.PositiveIntegerField(blank=True, help_text='개봉 시 확정 캐시(개봉 전 null)', null=True)),
                ('opened_via_ad', models.BooleanField(default=False, help_text='광고 보고 개봉한 상자인지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_boxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '캐시상자',
                'verbose_name_plural': '캐시상자',
                'indexes': [models.Index(fields=['user', 'status'], name='idx_cashbox_user_status')],
            },
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quiz_count', models.PositiveIntegerField(default=0, help_text='당일 푼 문제 수')),
                ('correct_count', models.PositiveIntegerField(default=0, help_text='당일 정답 수')),
                ('boxes_earned', models.PositiveIntegerField(default=0, help_text='당일 획득 상자 수(일일 상한 체크)')),
                ('cash_earned', models.BigIntegerField(default=0, help_text='당일 적립 캐시 합')),
                ('ad_bonus_count', models.PositiveIntegerField(default=0, help_text='당일 광고 보너스 횟수')),
                ('attended', models.BooleanField(default=False, help_text='당일 출석 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '데일리',
                'verbose_name_plural': '데일리',
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_daily_user_date')],
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('earn', '적립'), ('use', '사용')], max_length=4)),
                ('amount', models.BigIntegerField(help_text='항상 양수(절대값). 부호는 direction 이 결정')),
                ('reason', models.CharField(choices=[('quiz_box', '퀴즈 상자'), ('attendance', '출석'), ('streak', '연속출석'), ('ad_bonus', '광고 보너스'), ('exchange', '기프티콘 교환'), ('admin_adjust', '관리자 조정')], max_length=20)),
                ('ref_type', models.CharField(blank=True, help_text='관련 엔티티 종류(cash_box / gift_exchange / attendance …)', max_length=50)),
                ('ref_id', models.PositiveIntegerField(blank=True, help_text='관련 엔티티 id', null=True)),
                ('balance_after', models.BigIntegerField(help_text='거래 직후 잔액 스냅샷(감사용)')),
                ('ad_verified', models.BooleanField(default=False, help_text='광고 SSV 검증 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '원장',
                'verbose_name_plural': '원장',
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_ledger_user_created'), models.Index(fields=['user', 'direction', 'created_at'], name='idx_ledger_user_dir_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_amount_positive')],
            },
        ),
    ]
