# Generated by Django 6.0.6 on 2026-06-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendance',
            table='tbl_rewards_attendance',
        ),
        migrations.AlterModelTable(
            name='cashbox',
            table='tbl_rewards_cashbox',
        ),
        migrations.AlterModelTable(
            name='daily',
            table='tbl_rewards_daily',
        ),
        migrations.AlterModelTable(
            name='ledger',
            table='tbl_rewards_ledger',
        ),
        migrations.AlterModelTable(
            name='wallet',
            table='tbl_rewards_wallet',
        ),
    ]
