# Generated by Django 6.0.6 on 2026-06-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_alter_attendance_table_alter_cashbox_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='grade',
            field=models.CharField(choices=[('normal', '일반'), ('rare', '레어'), ('epic', '에픽'), ('legendary', '전설'), ('jackpot', '잭팟')], max_length=10),
        ),
    ]
