# Generated by Django 6.0.6 on 2026-07-02 14:14

from django.db import migrations, models


def collapse_old_grades(apps, schema_editor):
    """등급 2종화(normal/purple) 전, 미개봉 상자의 옛 등급을 normal로 치환.

    개봉 완료 상자는 이미 reward_cash가 확정이라 건드리지 않는다.
    """
    CashBox = apps.get_model('rewards', 'CashBox')
    CashBox.objects.filter(
        status='unopened',
        grade__in=['rare', 'epic', 'legendary', 'jackpot'],
    ).update(grade='normal')


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_alter_cashbox_grade'),
    ]

    operations = [
        migrations.RunPython(collapse_old_grades, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cashbox',
            name='grade',
            field=models.CharField(choices=[('normal', '일반'), ('purple', '보라')], max_length=10),
        ),
    ]
