# Generated by Django 6.0.6 on 2026-07-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_alter_cashbox_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='reason',
            field=models.CharField(choices=[('quiz_box', '퀴즈 상자'), ('quiz_milestone', '퀴즈 10문제 보너스'), ('attendance', '출석'), ('streak', '연속출석'), ('ad_bonus', '광고 보너스'), ('exchange', '기프티콘 교환'), ('admin_adjust', '관리자 조정')], max_length=20),
        ),
    ]
