# Generated by Django 6.0.6 on 2026-07-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_alter_ledger_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='grade',
            field=models.CharField(choices=[('normal', '일반'), ('purple', '보라'), ('burgundy', '버건디')], max_length=10),
        ),
    ]
