# Generated by Django 6.0.6 on 2026-07-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0007_alter_cashbox_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='burst_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='이 상자가 주는 보상 개수. 생성 시 확률로 결정된다(1 또는 3). 3이어도 인벤토리·광고 횟수는 1개로 센다(한 묶음). reward_cash는 그 합계.'),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='reward_breakdown',
            field=models.JSONField(blank=True, help_text='개봉 시 확정된 개별 보상 목록(예: [7, 12, 3]). 합이 reward_cash와 같다.', null=True),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='reward_cash',
            field=models.PositiveIntegerField(blank=True, help_text='개봉 시 확정 캐시 총합(개봉 전 null)', null=True),
        ),
    ]
