# Generated by Django 6.0.6 on 2026-07-24 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0008_cashbox_burst_count_cashbox_reward_breakdown_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='reason',
            field=models.CharField(choices=[('quiz_box', '퀴즈 상자'), ('quiz_milestone', '퀴즈 10문제 보너스'), ('attendance', '출석'), ('streak', '연속출석'), ('ad_bonus', '광고 보너스'), ('referral_inviter', '친구 초대 보상'), ('referral_invitee', '추천인 입력 보상'), ('exchange', '기프티콘 교환'), ('exchange_refund', '기프티콘 교환 환불'), ('admin_adjust', '관리자 조정')], max_length=20),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviter_cash', models.PositiveIntegerField(default=0, help_text='초대한 사람이 받은 캐시(상한 초과 시 0)')),
                ('invitee_cash', models.PositiveIntegerField(default=0, help_text='입력한 사람이 받은 캐시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitee', models.OneToOneField(help_text='코드를 입력한 사람. 1회 한정이라 OneToOne', on_delete=django.db.models.deletion.CASCADE, related_name='referral_used', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(help_text='코드 주인(초대한 사람)', on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '추천인',
                'verbose_name_plural': '추천인',
                'db_table': 'tbl_rewards_referral',
                'indexes': [models.Index(fields=['inviter'], name='idx_referral_inviter')],
            },
        ),
    ]
