# Generated by Django 6.0.6 on 2026-07-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0009_alter_ledger_reason_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='추천인 입력 시점의 기기 식별자. 기기당 1회 제한에 사용', max_length=128),
        ),
    ]
