# Generated by Django 6.0.6 on 2026-07-24 03:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0010_referral_device_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(condition=models.Q(('device_id', ''), _negated=True), fields=('device_id',), name='uniq_referral_device'),
        ),
    ]
