# Generated by Django 6.0.6 on 2026-07-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0012_remove_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='reason',
            field=models.CharField(choices=[('quiz_box', '퀴즈 상자'), ('quiz_milestone', '퀴즈 10문제 보너스'), ('ad_bonus', '광고 보너스'), ('referral_inviter', '친구 초대 보상'), ('referral_invitee', '추천인 입력 보상'), ('exchange', '기프티콘 교환'), ('exchange_refund', '기프티콘 교환 환불'), ('admin_adjust', '관리자 조정')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='ref_type',
            field=models.CharField(blank=True, help_text='관련 엔티티 종류(cash_box / gift_exchange …)', max_length=50),
        ),
    ]
