# Generated by Django 6.0.6 on 2026-08-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0014_remove_daily_ad_bonus_count_alter_ledger_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='grade',
            field=models.CharField(choices=[('normal', '일반'), ('blue', '파랑'), ('purple', '보라'), ('burgundy', '버건디')], max_length=10),
        ),
    ]
