"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import urllib.parse
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env (see .env.example).
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-@m+)9r%k9b50kf3$6r@p(3_o4o4k2y4%r+l=o^)8m*)$c%mziy',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if h.strip()
]

# DEBUG에선 안드로이드 에뮬레이터가 호스트를 가리키는 10.0.2.2 를 자동 허용한다.
# (없으면 앱→서버 요청이 ALLOWED_HOSTS 검사에서 400 Bad Request 로 막힌다.)
if DEBUG and '10.0.2.2' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('10.0.2.2')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'corsheaders',

    # Domain apps
    'accounts',
    'content',
    'learning',
    'rewards',
    'exchange',
    'notifications',
    'support',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 커스텀 유저 모델 (google_uid 기반 인증) — 최초 마이그레이션 전에 반드시 등록.
AUTH_USER_MODEL = 'accounts.User'

# 약관/개인정보 처리방침 현재 버전. 올리면 그 버전 동의가 없는 유저는 재동의 대상.
TERMS_VERSION = '1'
PRIVACY_VERSION = '1'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASE_URL (프로덕션/Supabase) 우선, 없으면 개별 DB_* 변수 사용.
# DB_ENGINE=sqlite 이면 SQLite로 폴백(로컬 편의용).
_db_url = os.environ.get('DATABASE_URL', '')
if _db_url:
    _u = urllib.parse.urlparse(_db_url)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _u.path.lstrip('/'),
            'USER': _u.username,
            'PASSWORD': _u.password,
            'HOST': _u.hostname,
            'PORT': _u.port or 5432,
            # Supabase Transaction pooler(pgBouncer)는 연결 유지를 지원하지 않음.
            'CONN_MAX_AGE': 0,
            'OPTIONS': {'sslmode': 'require'},
        }
    }
elif os.environ.get('DB_ENGINE', 'postgresql').lower() == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'japavoca'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
}

# Cloud Run은 HTTPS를 앞단 로드밸런서에서 처리하고 내부는 HTTP로 전달함.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
# https://www.django-rest-framework.org/
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


# Simple JWT
# https://django-rest-framework-simplejwt.readthedocs.io/
from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
}


# CORS (django-cors-headers)
# Comma-separated origins in CORS_ALLOWED_ORIGINS, e.g. http://localhost:8081
_cors = os.environ.get('CORS_ALLOWED_ORIGINS', '').strip()
if _cors:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors.split(',') if o.strip()]
else:
    # Dev default: allow all origins so the RN Metro/dev client can connect.
    CORS_ALLOW_ALL_ORIGINS = DEBUG


# Google OAuth — RN 클라이언트가 보낸 ID 토큰 검증 시 audience 로 사용.
# 비어있으면(dev) audience 검사를 건너뛴다.
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')

# 카카오 로그인 — 서버는 클라가 보낸 access token 으로 kapi.kakao.com 을 호출해 검증한다.
# (access token 검증만으로 충분해 별도 시크릿은 불필요. 클라 SDK 는 네이티브 앱키 필요.)
KAKAO_API_BASE = os.environ.get('KAKAO_API_BASE', 'https://kapi.kakao.com')

# 푸시(FCM) — 크리덴셜(firebase-admin + 서비스계정)이 준비되면 True 로. 현재는 stub.
FCM_ENABLED = os.environ.get('FCM_ENABLED', 'false').lower() in ('1', 'true', 'yes')


# 기프티콘 교환 발급사 — URL 이 비어있으면(dev) exchange.providers 가 Mock 응답.
GIFTICON_PROVIDER_URL = os.environ.get('GIFTICON_PROVIDER_URL', '')
GIFTICON_PROVIDER_KEY = os.environ.get('GIFTICON_PROVIDER_KEY', '')


# AdMob SSV(서버 보상 검증).
# ADMOB_SSV_VERIFY=false(dev) 면 서명 검증을 건너뛰고 통과로 본다(Mock).
ADMOB_APP_ID = os.environ.get('ADMOB_APP_ID', '')
ADMOB_SSV_VERIFY = os.environ.get('ADMOB_SSV_VERIFY', 'false').lower() in ('1', 'true', 'yes')
