# Generated by Django 6.0.6 on 2026-06-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='tbl_accounts_user',
        ),
    ]
