# Generated by Django 6.0.6 on 2026-06-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jlpt_level_kanji',
            field=models.CharField(blank=True, choices=[('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3'), ('N4', 'N4'), ('N5', 'N5')], help_text='한자 학습 급수(N1~N5)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='jlpt_level_word',
            field=models.CharField(blank=True, choices=[('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3'), ('N4', 'N4'), ('N5', 'N5')], help_text='단어 학습 급수(N1~N5)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kakao_uid',
            field=models.CharField(blank=True, help_text='카카오 식별자', max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('google', '구글'), ('kakao', '카카오')], default='google', help_text='가입/로그인 제공자', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='push_enabled',
            field=models.BooleanField(default=True, help_text='전체 푸시 수신'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_marketing',
            field=models.BooleanField(default=False, help_text='마케팅/이벤트 푸시(동의 기반)'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_quiz_reminder',
            field=models.BooleanField(default=True, help_text='학습 리마인더 푸시'),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_uid',
            field=models.CharField(blank=True, help_text='구글 OAuth 식별자', max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='selected_jlpt_level',
            field=models.CharField(blank=True, choices=[('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3'), ('N4', 'N4'), ('N5', 'N5')], help_text='(하위호환) 공통 학습 급수', max_length=2, null=True),
        ),
    ]
