# Generated by Django 6.0.6 on 2026-06-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_jlpt_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guest_uid',
            field=models.CharField(blank=True, help_text='게스트 기기 식별자(클라가 생성한 UUID). 소셜 연결 후에도 보존(기기 연속성).', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('guest', '게스트'), ('google', '구글'), ('kakao', '카카오')], default='google', help_text='가입/로그인 제공자', max_length=10),
        ),
    ]
