# Generated by Django 6.0.6 on 2026-06-26 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_guest_uid_alter_user_email_alter_user_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_version', models.CharField(help_text='동의한 이용약관 버전', max_length=20)),
                ('privacy_version', models.CharField(help_text='동의한 개인정보 처리방침 버전', max_length=20)),
                ('phone_data_agreed', models.BooleanField(default=False, help_text='휴대폰번호 데이터 동의(게스트 False)')),
                ('marketing_agreed', models.BooleanField(default=False, help_text='마케팅 정보 수신 동의(선택)')),
                ('phone_number', models.CharField(blank=True, help_text='휴대폰 번호(PII, 게스트 null)', max_length=20, null=True)),
                ('agreed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '동의 이력',
                'verbose_name_plural': '동의 이력',
                'db_table': 'tbl_accounts_consent',
                'ordering': ['-agreed_at'],
            },
        ),
    ]
