# Generated by Django 6.0.6 on 2026-06-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_consentagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_kana_hiragana',
            field=models.BooleanField(default=False, help_text='가나 트랙: 히라가나 포함'),
        ),
        migrations.AddField(
            model_name='user',
            name='study_kana_katakana',
            field=models.BooleanField(default=False, help_text='가나 트랙: 가타카나 포함'),
        ),
        migrations.AddField(
            model_name='user',
            name='study_level',
            field=models.CharField(blank=True, choices=[('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3'), ('N4', 'N4'), ('N5', 'N5')], help_text='study_mode 가 한자/한자단어/가나단어일 때의 급수', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='study_mode',
            field=models.CharField(blank=True, choices=[('kanji', '한자'), ('kanji_word', '한자단어'), ('kana_word', '가나단어'), ('kana', '가나')], help_text='현재 학습 트랙(단일). null=온보딩 미완료', max_length=12, null=True),
        ),
    ]
