# Generated by Django 6.0.6 on 2026-07-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_banned_add_withdrawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, help_text='내 추천 코드(남이 입력하는 값). 최초 조회 시 발급', max_length=12, null=True, unique=True),
        ),
    ]
