# Generated by Django 6.0.6 on 2026-08-04 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='push_quiz_reminder',
        ),
    ]
