# Generated by Django 6.0.6 on 2026-06-25 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('attendance', '출석'), ('streak', '연속출석'), ('box', '상자'), ('exchange', '교환'), ('quiz_reminder', '학습 리마인더'), ('system', '시스템')], default='system', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
                'db_table': 'tbl_notifications_notification',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='tbl_notific_user_id_315115_idx'), models.Index(fields=['user', 'created_at'], name='tbl_notific_user_id_b45c4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '푸시 토큰',
                'verbose_name_plural': '푸시 토큰',
                'db_table': 'tbl_notifications_pushtoken',
                'indexes': [models.Index(fields=['user', 'is_active'], name='tbl_notific_user_id_541b4b_idx')],
            },
        ),
    ]
