# Generated by Django 6.0.6 on 2026-07-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('attendance', '출석'), ('streak', '연속출석'), ('box', '상자'), ('exchange', '교환'), ('referral', '친구 초대'), ('inquiry', '문의 답변'), ('quiz_reminder', '학습 리마인더'), ('system', '시스템')], default='system', max_length=20),
        ),
    ]
