# Generated by Django 6.0.6 on 2026-06-23 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdRewardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_unit', models.CharField(help_text='AdMob 광고 유닛 ID', max_length=100)),
                ('ssv_signature', models.TextField(help_text='AdMob SSV 검증 데이터')),
                ('verified', models.BooleanField(default=False, help_text='검증 성공 여부')),
                ('reward_context', models.CharField(choices=[('box_open', '상자 개봉'), ('exchange', '교환'), ('bonus', '보너스')], max_length=10)),
                ('ref_id', models.PositiveIntegerField(blank=True, help_text='연결된 CashBox.id 또는 GiftExchange.id', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_reward_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '광고 보상 로그',
                'verbose_name_plural': '광고 보상 로그',
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_adlog_user_created')],
            },
        ),
        migrations.CreateModel(
            name='GiftExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(help_text='발급사 상품 코드', max_length=100)),
                ('cash_cost', models.BigIntegerField(help_text='차감 캐시')),
                ('provider', models.CharField(help_text='발급사(예: giftshow)', max_length=50)),
                ('provider_order_id', models.CharField(help_text='발급사 주문 id(멱등성 키)', max_length=200, unique=True)),
                ('status', models.CharField(choices=[('requested', '요청됨'), ('issued', '발급완료'), ('failed', '실패'), ('refunded', '환불됨')], default='requested', max_length=10)),
                ('ad_verified', models.BooleanField(default=False, help_text='교환 광고 시청 SSV 검증')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_exchanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '기프티콘 교환',
                'verbose_name_plural': '기프티콘 교환',
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_gift_user_created'), models.Index(fields=['status'], name='idx_gift_status')],
            },
        ),
    ]
