# Generated by Django 6.0.6 on 2026-06-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adrewardlog',
            table='tbl_exchange_adrewardlog',
        ),
        migrations.AlterModelTable(
            name='giftexchange',
            table='tbl_exchange_giftexchange',
        ),
    ]
