# Generated by Django 6.0.6 on 2026-06-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_alter_adrewardlog_table_alter_giftexchange_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrewardlog',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='AdMob SSV transaction_id(멱등성 키)', max_length=200, null=True, unique=True),
        ),
    ]
