# Generated by Django 6.0.6 on 2026-07-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_adrewardlog_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrewardlog',
            name='nonce',
            field=models.CharField(blank=True, help_text='클라 생성 일회용 nonce — 광고와 보상 액션의 명시 연결 키', max_length=64, null=True, unique=True),
        ),
    ]
