# Generated by Django 6.0.6 on 2026-06-23 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('word', '단어'), ('kanji', '한자')], max_length=10)),
                ('item_type', models.CharField(choices=[('word', '단어'), ('kanji', '한자')], max_length=10)),
                ('item_id', models.PositiveIntegerField()),
                ('question_type', models.CharField(choices=[('word_to_meaning', '단어→뜻'), ('meaning_to_word', '뜻→단어')], max_length=20)),
                ('is_correct', models.BooleanField()),
                ('answer_ms', models.PositiveIntegerField(blank=True, help_text='응답 소요 시간(ms), 어뷰징 탐지용', null=True)),
                ('jlpt_level', models.CharField(blank=True, help_text='출제 당시 문제 급수', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_logs', to='rewards.cashbox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '퀴즈 로그',
                'verbose_name_plural': '퀴즈 로그',
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_quizlog_user_created'), models.Index(fields=['created_at'], name='idx_quizlog_created')],
            },
        ),
        migrations.CreateModel(
            name='SrsState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('word', '단어'), ('kanji', '한자')], max_length=10)),
                ('item_id', models.PositiveIntegerField(help_text='Word.id 또는 Kanji.id')),
                ('ease', models.FloatField(default=2.5, help_text='SM-2 난이도 계수')),
                ('interval_days', models.PositiveIntegerField(default=1, help_text='현재 복습 간격(일)')),
                ('repetitions', models.PositiveIntegerField(default=0, help_text='연속 정답 횟수')),
                ('due_at', models.DateTimeField(help_text='다음 복습 예정 시각')),
                ('last_result', models.CharField(blank=True, choices=[('correct', '정답'), ('wrong', '오답')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SRS 상태',
                'verbose_name_plural': 'SRS 상태',
                'indexes': [models.Index(fields=['user', 'due_at'], name='idx_srs_user_due')],
                'constraints': [models.UniqueConstraint(fields=('user', 'item_type', 'item_id'), name='uniq_user_item')],
            },
        ),
    ]
