# Generated by Django 6.0.6 on 2026-06-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quizlog',
            table='tbl_learning_quizlog',
        ),
        migrations.AlterModelTable(
            name='srsstate',
            table='tbl_learning_srsstate',
        ),
    ]
