# Generated by Django 6.0.6 on 2026-06-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_quizlog_table_alter_srsstate_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlog',
            name='token_hash',
            field=models.CharField(blank=True, help_text='question_token 의 sha256. 재채점 방지용.', max_length=64, null=True, unique=True),
        ),
    ]
