# Generated by Django 6.0.6 on 2026-06-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_quizlog_token_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizlog',
            name='item_type',
            field=models.CharField(choices=[('word', '단어'), ('kanji', '한자'), ('kana', '가나')], max_length=10),
        ),
        migrations.AlterField(
            model_name='quizlog',
            name='mode',
            field=models.CharField(choices=[('word', '단어'), ('kanji', '한자'), ('kana', '가나')], max_length=10),
        ),
        migrations.AlterField(
            model_name='srsstate',
            name='item_type',
            field=models.CharField(choices=[('word', '단어'), ('kanji', '한자'), ('kana', '가나')], max_length=10),
        ),
    ]
