# Generated by Django 6.0.6 on 2026-06-27 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_quizlog_item_type_alter_quizlog_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('boxes_earned', models.PositiveIntegerField(default=0)),
                ('answered_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '퀴즈 세트',
                'verbose_name_plural': '퀴즈 세트',
                'db_table': 'tbl_learning_quizset',
            },
        ),
        migrations.CreateModel(
            name='QuizSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('item_type', models.CharField(choices=[('word', '단어'), ('kanji', '한자'), ('kana', '가나')], max_length=10)),
                ('word_type', models.CharField(blank=True, max_length=10, null=True)),
                ('item_id', models.PositiveIntegerField()),
                ('question_type', models.CharField(max_length=20)),
                ('correct_index', models.PositiveIntegerField()),
                ('prompt', models.CharField(blank=True, max_length=200)),
                ('reading', models.CharField(blank=True, max_length=100)),
                ('jlpt_level', models.CharField(blank=True, max_length=2)),
                ('choices_json', models.JSONField(default=list, help_text='[{index, text}, ...] 셔플 완료 순서')),
                ('answered', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('quiz_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.quizset')),
            ],
            options={
                'verbose_name': '세트 문항',
                'verbose_name_plural': '세트 문항',
                'db_table': 'tbl_learning_quizsetitem',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('word', '단어'), ('kanji', '한자'), ('kana', '가나')], max_length=10)),
                ('item_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '북마크',
                'verbose_name_plural': '북마크',
                'db_table': 'tbl_learning_bookmark',
                'constraints': [models.UniqueConstraint(fields=('user', 'item_type', 'item_id'), name='uniq_bookmark_user_item')],
            },
        ),
        migrations.AddIndex(
            model_name='quizset',
            index=models.Index(fields=['user', 'completed_at'], name='idx_quizset_user_completed'),
        ),
        migrations.AddConstraint(
            model_name='quizsetitem',
            constraint=models.UniqueConstraint(fields=('quiz_set', 'order'), name='uniq_quizset_item_order'),
        ),
    ]
