# Generated by Django 6.0.6 on 2026-06-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_add_quizset_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizset',
            name='abandoned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
