# Generated by Django 6.0.6 on 2026-07-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at'], 'verbose_name': '문의', 'verbose_name_plural': '문의'},
        ),
    ]
